{{- if (.Values.installNamespace) -}}
---
###
### Linkerd Viz Extension Namespace
###
kind: Namespace
apiVersion: v1
metadata:
  name: {{.Values.namespace}}
  labels:
    {{ include "partials.labels.extension" "linkerd-viz" }}
  annotations:
    {{- if .Values.prometheusUrl }}
    viz.linkerd.io/external-prometheus: {{.Values.prometheusUrl}}
    {{- end }}
    {{ include "partials.annotations.proxy-inject-enabled" . }}
{{ end -}}
