{{- if (.Values.installNamespace) -}}
---
###
### Linkerd Namespace
###
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}
  annotations:
    {{ include "partials.annotations.proxy-inject-disabled" . }}
  labels:
    {{ include "partials.labels.is-control-plane" . }}
    config.linkerd.io/admission-webhooks: disabled
    {{ include "partials.labels.controller-ns" . }}
{{ end -}}
